import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.argv[2] || '@electric-sql/pglite');
const db = new PGlite();
await db.exec(`
create role anon; create role authenticated;
create schema auth; create schema storage;
create table auth.users(id uuid primary key);
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
create function auth.uid() returns uuid language sql stable as $$ select (auth.jwt()->>'sub')::uuid $$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,unique(bucket_id,name));
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql immutable as $$ select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1] $$;
create publication supabase_realtime;
`);
await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
// Reapplying the versioned migration must also succeed.
await db.exec(await readFile(new URL('../migrations/20261002_secure_sessions.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20261002_team_live_tracking.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20261002_transport_water_quality.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20261002_secure_sessions.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20261002_team_live_tracking.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20261002_transport_water_quality.sql',import.meta.url),'utf8'));
await db.exec(`grant usage on schema public,auth,storage to authenticated;
grant select,insert,update,delete on all tables in schema public,storage to authenticated;`);
const owner='00000000-0000-0000-0000-000000000001';
const student='00000000-0000-0000-0000-000000000002';
const outsider='00000000-0000-0000-0000-000000000003';
const teammate='00000000-0000-0000-0000-000000000004';
await db.query('insert into auth.users(id) values ($1),($2),($3),($4)',[owner,student,outsider,teammate]);
async function login(id,anonymous=false) {
  await db.exec('reset role');
  await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,is_anonymous:anonymous})]);
  await db.exec('set role authenticated');
}
async function denied(sql,params=[]) { await assert.rejects(()=>db.query(sql,params)); }
const cp=[{name:'Dock',lat:-6.2,lng:106.8,radius_m:75,instructions:'Check oxygen',requires_photo:true,requires_temperature:true,requires_weight:true}];
await login(student,true);
await denied('select * from create_field_session($1,$2,$3)',['ABC234','Forged',JSON.stringify(cp)]);
await login(owner);
await denied('select * from create_field_session($1,$2,$3)',['DEF567','Invalid route',JSON.stringify([...cp,{...cp[0],lat:999}])]);
assert.equal((await db.query("select * from tracking_sessions where code='DEF567'")).rows.length,0);
const {rows:[session]}=await db.query('select * from create_field_session($1,$2,$3)',['ABC234','Practical',JSON.stringify(cp)]);
const {rows:[checkpoint]}=await db.query('select * from checkpoints where session_id=$1',[session.id]);
assert.equal(checkpoint.instructions,'Check oxygen');
assert.equal(checkpoint.order_index,1);
await denied('select * from join_field_session($1,$2,$3)',['ABC234','Owner','Team']);
await db.query('select save_field_checkpoint($1)',[JSON.stringify({...checkpoint,instructions:'Check oxygen and temperature'})]);
assert.equal((await db.query('select instructions from checkpoints where id=$1',[checkpoint.id])).rows[0].instructions,'Check oxygen and temperature');
await login(outsider,true);
assert.equal((await db.query('select * from tracking_sessions')).rows.length,0);
await denied('insert into session_participants(session_id,user_id,role) values($1,$2,$3)',[session.id,outsider,'lecturer']);
await denied('select close_field_session($1)',[session.id]);
await login(student,true);
await db.query('select * from join_field_session($1,$2,$3)',['ABC234','Ayu','Team A']);
await denied('select save_field_checkpoint($1)',[JSON.stringify(checkpoint)]);
await denied('insert into checkpoints(session_id,name,lat,lng) values($1,$2,0,0)',[session.id,'Forged checkpoint']);
const current=(await db.query("select now()-interval '1 minute' as at")).rows[0].at;
const previous=(await db.query("select now()-interval '2 minutes' as at")).rows[0].at;
await db.query("insert into live_positions(session_id,user_id,display_name,lat,lng,marker_type,event_at) values($1,$2,$3,-6.2,106.8,'horse',$4)",[session.id,student,'Forged name',current.toISOString()]);
await login(teammate,true);
await db.query('select * from join_field_session($1,$2,$3)',['ABC234','Bima','Team B']);
await db.query('insert into live_positions(session_id,user_id,display_name,lat,lng,event_at) values($1,$2,$3,-6.21,106.81,$4)',[session.id,teammate,'Forged name',current.toISOString()]);
await login(student,true);
assert.equal((await db.query('select display_name from live_positions')).rows[0].display_name,'Ayu');
assert.equal((await db.query('select count(*)::int n from live_positions')).rows[0].n,2,'students in different teams can see each other while the session is active');
assert.equal((await db.query('select marker_type from live_positions where user_id=$1',[student])).rows[0].marker_type,'horse');
await denied("insert into live_positions(session_id,user_id,lat,lng,marker_type) values($1,$2,0,0,'dragon')",[session.id,student]);
await db.query('update live_positions set lat=0,event_at=$1 where session_id=$2',[previous.toISOString(),session.id]);
assert.equal((await db.query('select lat from live_positions')).rows[0].lat,-6.2);
const recordId='00000000-0000-0000-0000-000000000004';
const path=`${session.id}/${student}/${recordId}.jpg`;
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['evidence',path]);
const record={id:recordId,session_id:session.id,user_id:student,checkpoint_id:checkpoint.id,display_name:'Ayu',team:'Team A',photo_path:path,temperature_c:25,total_fish:42,ph:7.4,dissolved_oxygen:6.3,condition:'GOOD',lat:0,lng:0};
await db.query('select submit_field_evidence($1)',[JSON.stringify(record)]);
await db.query('select submit_field_evidence($1)',[JSON.stringify(record)]);
assert.equal((await db.query('select count(*)::int n from submissions')).rows[0].n,1);
assert.equal((await db.query('select exception_reason from submissions')).rows[0].exception_reason,'Outside checkpoint radius');
assert.deepEqual((await db.query('select total_fish,ph,dissolved_oxygen from submissions')).rows[0],{total_fish:42,ph:7.4,dissolved_oxygen:6.3});
await denied('select submit_field_evidence($1)',[JSON.stringify({...record,id:'00000000-0000-0000-0000-000000000006',ph:15})]);
await login(outsider,true);
assert.equal((await db.query('select * from submissions')).rows.length,0);
assert.equal((await db.query('select * from live_positions')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await denied('insert into storage.objects(bucket_id,name) values($1,$2)',['evidence',`${session.id}/${student}/stolen.jpg`]);
await denied('select submit_field_evidence($1)',[JSON.stringify(record)]);
await login(owner);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
assert.equal((await db.query('select * from session_participants')).rows.length,3);
await db.query('select close_field_session($1)',[session.id]);
await login(student,true);
assert.equal((await db.query('select * from live_positions')).rows.length,0,'student location visibility ends when the session closes');
await denied('select * from join_field_session($1,$2,$3)',['ABC234','Ayu','Team A']);
await denied('select submit_field_evidence($1)',[JSON.stringify({...record,id:'00000000-0000-0000-0000-000000000005'})]);
await db.query('select submit_field_evidence($1)',[JSON.stringify(record)]);
await db.close();
console.log('PASS: atomic sessions, owner authorization, team-wide location visibility, marker validation, validated water-quality submissions, scoped evidence, idempotent retries, closed sessions and repeatable migrations');
